[build]
builder = "nixpacks"

[deploy]
# Start command for webhook bot - UPDATED
startCommand = "python bot_webhook.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
